### ISSUE TITLE
SDK无法正常拉取

### ISSUE THREAD

**Issue by imyouzhen** [tianlian0/duplicate-check-sample#1]
提示仓库https://maven.dreamspark.com.cn/repository/maven-releases没有这个sdk。

**Comment by tianlian0** [comment]
有3种可能的情况：
1、maven的setting文件中配置了镜像，并且mirrorOf中配置为*，这样会导致pom里配置的仓库地址不生效。这种情况在setting文件的mirrors标签中加上我们的maven仓库私服即可；
2、配置了主setting文件，导致子setting文件和pom中配置的私有仓库不生效。这种情况删掉主setting即可。
3、仓库正在对jar包进行patch更新。这种情况稍等10分钟再试就可以解决；

**Comment by MSN04-SAZABI** [comment]
您好我是一名在读学生，算是初学者
Dependency 'com.xincheck:duplicate-check-pro:0.5.3' not found 
请问这个应该怎么解决呢

**Comment by Tang1705** [comment]
> 您好我是一名在读学生，算是初学者
> Dependency 'com.xincheck:duplicate-check-pro:0.5.3' not found
> 请问这个应该怎么解决呢

您好，已对相关代码进行更新，请同步后再次试用
