### ISSUE TITLE
业界广泛认可的ContinuityCheck算法，但是没找到相关原理诶

### ISSUE THREAD

**Issue by shuangt** [tianlian0/duplicate-check-sample#2]
最近在看查重，项目介绍说用的业界广泛认可的ContinuityCheck算法，请教一下：
1、ContinuityCheck算法是一类算法还是一个算法？
2、如果是一个算法的话，相关原理在哪儿都没找到；如果是一类算法的话，代表性的有哪些呢？
目前看了些基础的算法，如simhash、minhash这些，知网的模糊算法也不清楚是怎么实现的。。。

**Comment by tianlian0** [comment]
1.是基于某些算法原理实现的受著作权保护的专有算法。
2.本项目仅为XINCHECK SDK的使用示例，项目问题欢迎讨论，SDK问题请通过XINCHECK官网联系工作人员咨询。商用软件并非科研论文或学习教程，具体算法的原理和细节可能涉及到专利及商业秘密，请您自行搜索。
