### ISSUE TITLE
可以简述一下算法核心思想吗

### ISSUE THREAD

**Issue by 601480999** [tianlian0/duplicate-check-sample#4]
非常棒的工作，可以大概说一下算法的核心思想吗，非常感谢

**Comment by Tang1705** [comment]
1.是基于某些算法原理实现的受著作权保护的专有算法。
2.本项目仅为XINCHECK SDK的使用示例，项目问题欢迎讨论，SDK问题请通过XINCHECK官网联系工作人员咨询。商用软件并非科研论文或学习教程，具体算法的原理和细节可能涉及到专利及商业秘密，请您自行搜索。
Duplicate of #

**Comment by Tang1705** [comment]
1.是基于某些算法原理实现的受著作权保护的专有算法。
2.本项目仅为XINCHECK SDK的使用示例，项目问题欢迎讨论，SDK问题请通过XINCHECK官网联系工作人员咨询。商用软件并非科研论文或学习教程，具体算法的原理和细节可能涉及到专利及商业秘密，请您自行搜索。
